// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProfileRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate          string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"` // Format: DD-MM-YYYY
	BirthTime          string                 `protobuf:"bytes,5,opt,name=birth_time,json=birthTime,proto3" json:"birth_time,omitempty"`
	BirthPlace         string                 `protobuf:"bytes,6,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
	Nakshatra          string                 `protobuf:"bytes,7,opt,name=nakshatra,proto3" json:"nakshatra,omitempty"`
	Rashi              string                 `protobuf:"bytes,8,opt,name=rashi,proto3" json:"rashi,omitempty"`
	Gender             string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Height             string                 `protobuf:"bytes,10,opt,name=height,proto3" json:"height,omitempty"`
	FatherName         string                 `protobuf:"bytes,11,opt,name=father_name,json=fatherName,proto3" json:"father_name,omitempty"`
	MotherName         string                 `protobuf:"bytes,12,opt,name=mother_name,json=motherName,proto3" json:"mother_name,omitempty"`
	TotalFamilyMembers int32                  `protobuf:"varint,13,opt,name=total_family_members,json=totalFamilyMembers,proto3" json:"total_family_members,omitempty"`
	Qualification      string                 `protobuf:"bytes,14,opt,name=qualification,proto3" json:"qualification,omitempty"`
	Degree             string                 `protobuf:"bytes,15,opt,name=degree,proto3" json:"degree,omitempty"`
	College            string                 `protobuf:"bytes,16,opt,name=college,proto3" json:"college,omitempty"`
	Designation        string                 `protobuf:"bytes,17,opt,name=designation,proto3" json:"designation,omitempty"`
	CompanyAndCity     string                 `protobuf:"bytes,18,opt,name=company_and_city,json=companyAndCity,proto3" json:"company_and_city,omitempty"`
	City               string                 `protobuf:"bytes,19,opt,name=city,proto3" json:"city,omitempty"`
	District           string                 `protobuf:"bytes,20,opt,name=district,proto3" json:"district,omitempty"`
	State              string                 `protobuf:"bytes,21,opt,name=state,proto3" json:"state,omitempty"`
	MaritalStatus      string                 `protobuf:"bytes,22,opt,name=marital_status,json=maritalStatus,proto3" json:"marital_status,omitempty"`
	AddDetails         string                 `protobuf:"bytes,23,opt,name=add_details,json=addDetails,proto3" json:"add_details,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateProfileRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreateProfileRequest) GetBirthTime() string {
	if x != nil {
		return x.BirthTime
	}
	return ""
}

func (x *CreateProfileRequest) GetBirthPlace() string {
	if x != nil {
		return x.BirthPlace
	}
	return ""
}

func (x *CreateProfileRequest) GetNakshatra() string {
	if x != nil {
		return x.Nakshatra
	}
	return ""
}

func (x *CreateProfileRequest) GetRashi() string {
	if x != nil {
		return x.Rashi
	}
	return ""
}

func (x *CreateProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateProfileRequest) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *CreateProfileRequest) GetFatherName() string {
	if x != nil {
		return x.FatherName
	}
	return ""
}

func (x *CreateProfileRequest) GetMotherName() string {
	if x != nil {
		return x.MotherName
	}
	return ""
}

func (x *CreateProfileRequest) GetTotalFamilyMembers() int32 {
	if x != nil {
		return x.TotalFamilyMembers
	}
	return 0
}

func (x *CreateProfileRequest) GetQualification() string {
	if x != nil {
		return x.Qualification
	}
	return ""
}

func (x *CreateProfileRequest) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *CreateProfileRequest) GetCollege() string {
	if x != nil {
		return x.College
	}
	return ""
}

func (x *CreateProfileRequest) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

func (x *CreateProfileRequest) GetCompanyAndCity() string {
	if x != nil {
		return x.CompanyAndCity
	}
	return ""
}

func (x *CreateProfileRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateProfileRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CreateProfileRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateProfileRequest) GetMaritalStatus() string {
	if x != nil {
		return x.MaritalStatus
	}
	return ""
}

func (x *CreateProfileRequest) GetAddDetails() string {
	if x != nil {
		return x.AddDetails
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateProfileRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate          string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"` // Format: DD-MM-YYYY
	BirthTime          string                 `protobuf:"bytes,5,opt,name=birth_time,json=birthTime,proto3" json:"birth_time,omitempty"`
	BirthPlace         string                 `protobuf:"bytes,6,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
	Nakshatra          string                 `protobuf:"bytes,7,opt,name=nakshatra,proto3" json:"nakshatra,omitempty"`
	Rashi              string                 `protobuf:"bytes,8,opt,name=rashi,proto3" json:"rashi,omitempty"`
	Gender             string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Height             string                 `protobuf:"bytes,10,opt,name=height,proto3" json:"height,omitempty"`
	FatherName         string                 `protobuf:"bytes,11,opt,name=father_name,json=fatherName,proto3" json:"father_name,omitempty"`
	MotherName         string                 `protobuf:"bytes,12,opt,name=mother_name,json=motherName,proto3" json:"mother_name,omitempty"`
	TotalFamilyMembers int32                  `protobuf:"varint,13,opt,name=total_family_members,json=totalFamilyMembers,proto3" json:"total_family_members,omitempty"`
	Qualification      string                 `protobuf:"bytes,14,opt,name=qualification,proto3" json:"qualification,omitempty"`
	Degree             string                 `protobuf:"bytes,15,opt,name=degree,proto3" json:"degree,omitempty"`
	College            string                 `protobuf:"bytes,16,opt,name=college,proto3" json:"college,omitempty"`
	Designation        string                 `protobuf:"bytes,17,opt,name=designation,proto3" json:"designation,omitempty"`
	CompanyAndCity     string                 `protobuf:"bytes,18,opt,name=company_and_city,json=companyAndCity,proto3" json:"company_and_city,omitempty"`
	City               string                 `protobuf:"bytes,19,opt,name=city,proto3" json:"city,omitempty"`
	District           string                 `protobuf:"bytes,20,opt,name=district,proto3" json:"district,omitempty"`
	State              string                 `protobuf:"bytes,21,opt,name=state,proto3" json:"state,omitempty"`
	MaritalStatus      string                 `protobuf:"bytes,22,opt,name=marital_status,json=maritalStatus,proto3" json:"marital_status,omitempty"`
	AddDetails         string                 `protobuf:"bytes,23,opt,name=add_details,json=addDetails,proto3" json:"add_details,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateProfileRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *UpdateProfileRequest) GetBirthTime() string {
	if x != nil {
		return x.BirthTime
	}
	return ""
}

func (x *UpdateProfileRequest) GetBirthPlace() string {
	if x != nil {
		return x.BirthPlace
	}
	return ""
}

func (x *UpdateProfileRequest) GetNakshatra() string {
	if x != nil {
		return x.Nakshatra
	}
	return ""
}

func (x *UpdateProfileRequest) GetRashi() string {
	if x != nil {
		return x.Rashi
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateProfileRequest) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *UpdateProfileRequest) GetFatherName() string {
	if x != nil {
		return x.FatherName
	}
	return ""
}

func (x *UpdateProfileRequest) GetMotherName() string {
	if x != nil {
		return x.MotherName
	}
	return ""
}

func (x *UpdateProfileRequest) GetTotalFamilyMembers() int32 {
	if x != nil {
		return x.TotalFamilyMembers
	}
	return 0
}

func (x *UpdateProfileRequest) GetQualification() string {
	if x != nil {
		return x.Qualification
	}
	return ""
}

func (x *UpdateProfileRequest) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *UpdateProfileRequest) GetCollege() string {
	if x != nil {
		return x.College
	}
	return ""
}

func (x *UpdateProfileRequest) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

func (x *UpdateProfileRequest) GetCompanyAndCity() string {
	if x != nil {
		return x.CompanyAndCity
	}
	return ""
}

func (x *UpdateProfileRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateProfileRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UpdateProfileRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateProfileRequest) GetMaritalStatus() string {
	if x != nil {
		return x.MaritalStatus
	}
	return ""
}

func (x *UpdateProfileRequest) GetAddDetails() string {
	if x != nil {
		return x.AddDetails
	}
	return ""
}

type ProfileResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate          string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"` // Format: DD-MM-YYYY
	BirthTime          string                 `protobuf:"bytes,5,opt,name=birth_time,json=birthTime,proto3" json:"birth_time,omitempty"`
	BirthPlace         string                 `protobuf:"bytes,6,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
	Nakshatra          string                 `protobuf:"bytes,7,opt,name=nakshatra,proto3" json:"nakshatra,omitempty"`
	Rashi              string                 `protobuf:"bytes,8,opt,name=rashi,proto3" json:"rashi,omitempty"`
	Gender             string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Height             string                 `protobuf:"bytes,10,opt,name=height,proto3" json:"height,omitempty"`
	FatherName         string                 `protobuf:"bytes,11,opt,name=father_name,json=fatherName,proto3" json:"father_name,omitempty"`
	MotherName         string                 `protobuf:"bytes,12,opt,name=mother_name,json=motherName,proto3" json:"mother_name,omitempty"`
	TotalFamilyMembers int32                  `protobuf:"varint,13,opt,name=total_family_members,json=totalFamilyMembers,proto3" json:"total_family_members,omitempty"`
	Qualification      string                 `protobuf:"bytes,14,opt,name=qualification,proto3" json:"qualification,omitempty"`
	Degree             string                 `protobuf:"bytes,15,opt,name=degree,proto3" json:"degree,omitempty"`
	College            string                 `protobuf:"bytes,16,opt,name=college,proto3" json:"college,omitempty"`
	Designation        string                 `protobuf:"bytes,17,opt,name=designation,proto3" json:"designation,omitempty"`
	CompanyAndCity     string                 `protobuf:"bytes,18,opt,name=company_and_city,json=companyAndCity,proto3" json:"company_and_city,omitempty"`
	City               string                 `protobuf:"bytes,19,opt,name=city,proto3" json:"city,omitempty"`
	District           string                 `protobuf:"bytes,20,opt,name=district,proto3" json:"district,omitempty"`
	State              string                 `protobuf:"bytes,21,opt,name=state,proto3" json:"state,omitempty"`
	MaritalStatus      string                 `protobuf:"bytes,22,opt,name=marital_status,json=maritalStatus,proto3" json:"marital_status,omitempty"`
	AddDetails         string                 `protobuf:"bytes,23,opt,name=add_details,json=addDetails,proto3" json:"add_details,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_proto_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ProfileResponse) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *ProfileResponse) GetBirthTime() string {
	if x != nil {
		return x.BirthTime
	}
	return ""
}

func (x *ProfileResponse) GetBirthPlace() string {
	if x != nil {
		return x.BirthPlace
	}
	return ""
}

func (x *ProfileResponse) GetNakshatra() string {
	if x != nil {
		return x.Nakshatra
	}
	return ""
}

func (x *ProfileResponse) GetRashi() string {
	if x != nil {
		return x.Rashi
	}
	return ""
}

func (x *ProfileResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ProfileResponse) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *ProfileResponse) GetFatherName() string {
	if x != nil {
		return x.FatherName
	}
	return ""
}

func (x *ProfileResponse) GetMotherName() string {
	if x != nil {
		return x.MotherName
	}
	return ""
}

func (x *ProfileResponse) GetTotalFamilyMembers() int32 {
	if x != nil {
		return x.TotalFamilyMembers
	}
	return 0
}

func (x *ProfileResponse) GetQualification() string {
	if x != nil {
		return x.Qualification
	}
	return ""
}

func (x *ProfileResponse) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *ProfileResponse) GetCollege() string {
	if x != nil {
		return x.College
	}
	return ""
}

func (x *ProfileResponse) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

func (x *ProfileResponse) GetCompanyAndCity() string {
	if x != nil {
		return x.CompanyAndCity
	}
	return ""
}

func (x *ProfileResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ProfileResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *ProfileResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProfileResponse) GetMaritalStatus() string {
	if x != nil {
		return x.MaritalStatus
	}
	return ""
}

func (x *ProfileResponse) GetAddDetails() string {
	if x != nil {
		return x.AddDetails
	}
	return ""
}

var File_proto_profile_proto protoreflect.FileDescriptor

const file_proto_profile_proto_rawDesc = "" +
	"\n" +
	"\x13proto/profile.proto\x12\aprofile\"\xbe\x05\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x1d\n" +
	"\n" +
	"birth_time\x18\x05 \x01(\tR\tbirthTime\x12\x1f\n" +
	"\vbirth_place\x18\x06 \x01(\tR\n" +
	"birthPlace\x12\x1c\n" +
	"\tnakshatra\x18\a \x01(\tR\tnakshatra\x12\x14\n" +
	"\x05rashi\x18\b \x01(\tR\x05rashi\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\tR\x06height\x12\x1f\n" +
	"\vfather_name\x18\v \x01(\tR\n" +
	"fatherName\x12\x1f\n" +
	"\vmother_name\x18\f \x01(\tR\n" +
	"motherName\x120\n" +
	"\x14total_family_members\x18\r \x01(\x05R\x12totalFamilyMembers\x12$\n" +
	"\rqualification\x18\x0e \x01(\tR\rqualification\x12\x16\n" +
	"\x06degree\x18\x0f \x01(\tR\x06degree\x12\x18\n" +
	"\acollege\x18\x10 \x01(\tR\acollege\x12 \n" +
	"\vdesignation\x18\x11 \x01(\tR\vdesignation\x12(\n" +
	"\x10company_and_city\x18\x12 \x01(\tR\x0ecompanyAndCity\x12\x12\n" +
	"\x04city\x18\x13 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x14 \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\x15 \x01(\tR\x05state\x12%\n" +
	"\x0emarital_status\x18\x16 \x01(\tR\rmaritalStatus\x12\x1f\n" +
	"\vadd_details\x18\x17 \x01(\tR\n" +
	"addDetails\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xbe\x05\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x1d\n" +
	"\n" +
	"birth_time\x18\x05 \x01(\tR\tbirthTime\x12\x1f\n" +
	"\vbirth_place\x18\x06 \x01(\tR\n" +
	"birthPlace\x12\x1c\n" +
	"\tnakshatra\x18\a \x01(\tR\tnakshatra\x12\x14\n" +
	"\x05rashi\x18\b \x01(\tR\x05rashi\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\tR\x06height\x12\x1f\n" +
	"\vfather_name\x18\v \x01(\tR\n" +
	"fatherName\x12\x1f\n" +
	"\vmother_name\x18\f \x01(\tR\n" +
	"motherName\x120\n" +
	"\x14total_family_members\x18\r \x01(\x05R\x12totalFamilyMembers\x12$\n" +
	"\rqualification\x18\x0e \x01(\tR\rqualification\x12\x16\n" +
	"\x06degree\x18\x0f \x01(\tR\x06degree\x12\x18\n" +
	"\acollege\x18\x10 \x01(\tR\acollege\x12 \n" +
	"\vdesignation\x18\x11 \x01(\tR\vdesignation\x12(\n" +
	"\x10company_and_city\x18\x12 \x01(\tR\x0ecompanyAndCity\x12\x12\n" +
	"\x04city\x18\x13 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x14 \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\x15 \x01(\tR\x05state\x12%\n" +
	"\x0emarital_status\x18\x16 \x01(\tR\rmaritalStatus\x12\x1f\n" +
	"\vadd_details\x18\x17 \x01(\tR\n" +
	"addDetails\"\xb9\x05\n" +
	"\x0fProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x1d\n" +
	"\n" +
	"birth_time\x18\x05 \x01(\tR\tbirthTime\x12\x1f\n" +
	"\vbirth_place\x18\x06 \x01(\tR\n" +
	"birthPlace\x12\x1c\n" +
	"\tnakshatra\x18\a \x01(\tR\tnakshatra\x12\x14\n" +
	"\x05rashi\x18\b \x01(\tR\x05rashi\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\tR\x06height\x12\x1f\n" +
	"\vfather_name\x18\v \x01(\tR\n" +
	"fatherName\x12\x1f\n" +
	"\vmother_name\x18\f \x01(\tR\n" +
	"motherName\x120\n" +
	"\x14total_family_members\x18\r \x01(\x05R\x12totalFamilyMembers\x12$\n" +
	"\rqualification\x18\x0e \x01(\tR\rqualification\x12\x16\n" +
	"\x06degree\x18\x0f \x01(\tR\x06degree\x12\x18\n" +
	"\acollege\x18\x10 \x01(\tR\acollege\x12 \n" +
	"\vdesignation\x18\x11 \x01(\tR\vdesignation\x12(\n" +
	"\x10company_and_city\x18\x12 \x01(\tR\x0ecompanyAndCity\x12\x12\n" +
	"\x04city\x18\x13 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x14 \x01(\tR\bdistrict\x12\x14\n" +
	"\x05state\x18\x15 \x01(\tR\x05state\x12%\n" +
	"\x0emarital_status\x18\x16 \x01(\tR\rmaritalStatus\x12\x1f\n" +
	"\vadd_details\x18\x17 \x01(\tR\n" +
	"addDetails2\xe8\x01\n" +
	"\x0eProfileService\x12H\n" +
	"\rCreateProfile\x12\x1d.profile.CreateProfileRequest\x1a\x18.profile.ProfileResponse\x12B\n" +
	"\n" +
	"GetProfile\x12\x1a.profile.GetProfileRequest\x1a\x18.profile.ProfileResponse\x12H\n" +
	"\rUpdateProfile\x12\x1d.profile.UpdateProfileRequest\x1a\x18.profile.ProfileResponseB(Z&github.com/ssk-matrimony/proto/profileb\x06proto3"

var (
	file_proto_profile_proto_rawDescOnce sync.Once
	file_proto_profile_proto_rawDescData []byte
)

func file_proto_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_proto_rawDesc), len(file_proto_profile_proto_rawDesc)))
	})
	return file_proto_profile_proto_rawDescData
}

var file_proto_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_profile_proto_goTypes = []any{
	(*CreateProfileRequest)(nil), // 0: profile.CreateProfileRequest
	(*GetProfileRequest)(nil),    // 1: profile.GetProfileRequest
	(*UpdateProfileRequest)(nil), // 2: profile.UpdateProfileRequest
	(*ProfileResponse)(nil),      // 3: profile.ProfileResponse
}
var file_proto_profile_proto_depIdxs = []int32{
	0, // 0: profile.ProfileService.CreateProfile:input_type -> profile.CreateProfileRequest
	1, // 1: profile.ProfileService.GetProfile:input_type -> profile.GetProfileRequest
	2, // 2: profile.ProfileService.UpdateProfile:input_type -> profile.UpdateProfileRequest
	3, // 3: profile.ProfileService.CreateProfile:output_type -> profile.ProfileResponse
	3, // 4: profile.ProfileService.GetProfile:output_type -> profile.ProfileResponse
	3, // 5: profile.ProfileService.UpdateProfile:output_type -> profile.ProfileResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_profile_proto_init() }
func file_proto_profile_proto_init() {
	if File_proto_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_proto_rawDesc), len(file_proto_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_proto = out.File
	file_proto_profile_proto_goTypes = nil
	file_proto_profile_proto_depIdxs = nil
}
